Blast4-archive ::= {
  request {
    ident "2.2.29+",
    body queue-search {
      program "blastn",
      service "megablast",
      queries bioseq-set {
        seq-set {
          seq {
            id {
              local str "Query_1"
            },
            descr {
              user {
                type str "CFastaReader",
                data {
                  {
                    label str "DefLine",
                    data str ">Contig1"
                  }
                }
              },
              title "Contig1"
            },
            inst {
              repr raw,
              mol na,
              length 1920,
              seq-data ncbi2na '0C0300C0300C0300C0300C0300C0302C0300C0300C0380
08300C0102703C0301E040320C000F0FFF51F10E9F3B1380B37B37263CF3903300E67D4E9D9724
0925100795E4710114711483E03768061FF83EC034EF81FE1FE0E925CDE9A6704BF8784BBB87A4
BFDB90C445E3CF83B8303B3C303F393BCEC4C4C62C4C2C8CFC0D5E74D3FA5FFBFBC3C03BF5481E
C1E7B4063EFA7F16F9EF7EF76F3E7BEFBEF2FE7C433394300710CC0ED2CFEA65FBE7F3E3CFEFE0
FED7CFBE4BEFACF9EFBE78E979F93FC49CC3CB2D8BF240411FF9C7EFE7A7F39B9B3FE3BB331333
3BBBB933CB3B3B8C7C52BE6BE6BCF50EC392F87FD3FB033333F02D967A439F0CC5447C1ACCECFC
CCCCC5C4CFFE34D5430BB2B7D75DD127AAE3B44D35318184E11EDEF8FBE3F8008B493B780471BA
E58327E0AAD7592F7A6897F8CF1F2EF2CC44A4CC2FFDDA314074A7202E2B7F9423FA64EBA3F3C4
DC09C478C2B5092F6F82BA9FC37F444339D9C817CCE6336E8A74CD30C3E9821ECB757222647CAF
50D360CE5F4D614CF39F209C3139146D2F7D96DB91277528C78DA75A71C64DF27DFDFFFBF90328
7E7D7DF49CDACDCD53511EBEEB23641BD8033DF7D77DDFC71A4E93756FF1695F7FCC3EDA01430F
F9F0A711F022BA03DEF512643CCDAF94189BDF2222008888A88CC882'H
            }
          },
          seq {
            id {
              local str "Query_2"
            },
            descr {
              user {
                type str "CFastaReader",
                data {
                  {
                    label str "DefLine",
                    data str ">Contig2"
                  }
                }
              },
              title "Contig2"
            },
            inst {
              repr raw,
              mol na,
              length 1729,
              seq-data ncbi2na 'FC3DE7D018F9A9481EDDC4FEAE62344A413442F4B8C586
48D4443951228F7DFF746DA3A78E2400135A7B8F800A4214C84ED61FA2961EBEB8EFD00A2C2CCF
3CFAFE613DBE88ED0CB3810FE1FE1FFE2BF62231327B7DF4820E3B83AFE3310F7002C4BA2C41DC
09409F74BCCFBD2849F4D3A2F90A41EC77DEBDE8EDFE88203FBD30E54683617DBAAF6E95DA60AF
A441C534F5F55EA1C5B9E781EAF50B3E5E187C6E361FFEDF1F697A4C61702DE553114E3200889B
C206A21AC64D2BB1AFF0823423A988F9E2BAD0E09C1862082C60BA28033CDA82A4208DFD682F25
22AC3A5B92AB00C2EC3CF2F0299FD7F6EF934413FDD8714EFBE5D3FFF1E344F5C4A12F8BCEF23C
3A07FF70BF02A8FFF0B0030900CFF8AC3FEB503C04FD8233297F0FFDFF43CE03F002D0FB3FDFFF
CFFCC1CCF9FF72C3E003F8BE817C41C6000FD22FFCC3F0F403CC4CCC80F3A7C1CEDFCCACFBF005
3F0BF3F033023A9004FB5D7402EEE300DB1FD433ACB6100CE2CFFE313F73C8CE0EE33FCBFF1C33
BAB37F82CFF04473FF01C3F5C98F1BEC0050202A80FE833E0C33BF2CFD1C2A7F38CB40EFE94FC8
8C0C2020D8F080C8426BAC03C833330CCC4D1300'H
            }
          }
        }
      },
      subject database "Agla_Btl03082013.genome_new_ids.fa
 Ccap01172013-genome_new_ids.fa",
      algorithm-options {
        {
          name "EvalueThreshold",
          value cutoff e-value { 1, 10, 1 }
        },
        {
          name "MaskAtHash",
          value boolean TRUE
        },
        {
          name "DustFilteringLevel",
          value integer 20
        },
        {
          name "DustFilteringWindow",
          value integer 64
        },
        {
          name "DustFilteringLinker",
          value integer 1
        },
        {
          name "UngappedMode",
          value boolean FALSE
        },
        {
          name "HitlistSize",
          value integer 500
        },
        {
          name "EffectiveSearchSpace",
          value big-integer 2253100761450
        }
      },
      program-options {
        {
          name "LCaseMask",
          value query-mask {
            locations {
              packed-int {
                {
                  from 0,
                  to 154,
                  id local str "Query_1"
                },
                {
                  from 0,
                  to 154,
                  id local str "Query_1"
                },
                {
                  from 577,
                  to 639,
                  id local str "Query_1"
                },
                {
                  from 577,
                  to 639,
                  id local str "Query_1"
                },
                {
                  from 695,
                  to 755,
                  id local str "Query_1"
                },
                {
                  from 695,
                  to 755,
                  id local str "Query_1"
                },
                {
                  from 837,
                  to 900,
                  id local str "Query_1"
                },
                {
                  from 837,
                  to 900,
                  id local str "Query_1"
                },
                {
                  from 1016,
                  to 1037,
                  id local str "Query_1"
                },
                {
                  from 1016,
                  to 1037,
                  id local str "Query_1"
                },
                {
                  from 1884,
                  to 1917,
                  id local str "Query_1"
                },
                {
                  from 1884,
                  to 1917,
                  id local str "Query_1"
                }
              }
            },
            frame plus1
          }
        },
        {
          name "LCaseMask",
          value query-mask {
            locations {
              packed-int {
                {
                  from 979,
                  to 985,
                  id local str "Query_2"
                },
                {
                  from 979,
                  to 985,
                  id local str "Query_2"
                },
                {
                  from 1129,
                  to 1191,
                  id local str "Query_2"
                },
                {
                  from 1129,
                  to 1191,
                  id local str "Query_2"
                },
                {
                  from 1704,
                  to 1719,
                  id local str "Query_2"
                },
                {
                  from 1704,
                  to 1719,
                  id local str "Query_2"
                }
              }
            },
            frame plus1
          }
        }
      }
    }
  },
  results {
    alignments {
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 1920
          },
          {
            id str "e_value",
            value real { 0, 10, 0 }
          },
          {
            id str "bit_score",
            value real { 354668762672243, 10, -11 }
          },
          {
            id str "num_ident",
            value int 1920
          }
        },
        segs denseg {
          dim 2,
          numseg 1,
          ids {
            local str "Query_1",
            general {
              db "Ceratitis_capitata",
              tag str "cercap_NW_004522754.1"
            }
          },
          starts {
            0,
            0
          },
          lens {
            1920
          },
          strands {
            plus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 67
          },
          {
            id str "e_value",
            value real { 589445529162742, 10, -40 }
          },
          {
            id str "bit_score",
            value real { 124845820940355, 10, -12 }
          },
          {
            id str "num_ident",
            value int 108
          }
        },
        segs denseg {
          dim 2,
          numseg 5,
          ids {
            local str "Query_1",
            general {
              db "Ceratitis_capitata",
              tag str "cercap_NW_004523725.1"
            }
          },
          starts {
            1452,
            6209768,
            -1,
            6209787,
            1446,
            6209788,
            1445,
            -1,
            1344,
            6209794
          },
          lens {
            19,
            1,
            6,
            1,
            101
          },
          strands {
            minus,
            plus,
            minus,
            plus,
            minus,
            plus,
            minus,
            plus,
            minus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 59
          },
          {
            id str "e_value",
            value real { 165051384887403, 10, -35 }
          },
          {
            id str "bit_score",
            value real { 110072623721652, 10, -12 }
          },
          {
            id str "num_ident",
            value int 81
          }
        },
        segs denseg {
          dim 2,
          numseg 1,
          ids {
            local str "Query_1",
            general {
              db "Ceratitis_capitata",
              tag str "cercap_NW_004524323.1"
            }
          },
          starts {
            1340,
            28091
          },
          lens {
            92
          },
          strands {
            plus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 57
          },
          {
            id str "e_value",
            value real { 21350745625808, 10, -33 }
          },
          {
            id str "bit_score",
            value real { 106379324416977, 10, -12 }
          },
          {
            id str "num_ident",
            value int 79
          }
        },
        segs denseg {
          dim 2,
          numseg 1,
          ids {
            local str "Query_1",
            general {
              db "Ceratitis_capitata",
              tag str "cercap_NW_004523765.1"
            }
          },
          starts {
            1352,
            438715
          },
          lens {
            90
          },
          strands {
            minus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 51
          },
          {
            id str "e_value",
            value real { 462162461253104, 10, -31 }
          },
          {
            id str "bit_score",
            value real { 952994265029492, 10, -13 }
          },
          {
            id str "num_ident",
            value int 64
          }
        },
        segs denseg {
          dim 2,
          numseg 3,
          ids {
            local str "Query_1",
            general {
              db "Ceratitis_capitata",
              tag str "cercap_NW_004524146.1"
            }
          },
          starts {
            1385,
            488237,
            1384,
            -1,
            1354,
            488276
          },
          lens {
            39,
            1,
            30
          },
          strands {
            minus,
            plus,
            minus,
            plus,
            minus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 40
          },
          {
            id str "e_value",
            value real { 602089387820602, 10, -25 }
          },
          {
            id str "bit_score",
            value real { 749862803272326, 10, -13 }
          },
          {
            id str "num_ident",
            value int 83
          }
        },
        segs denseg {
          dim 2,
          numseg 5,
          ids {
            local str "Query_1",
            general {
              db "Ceratitis_capitata",
              tag str "cercap_NW_004523714.1"
            }
          },
          starts {
            1349,
            896209,
            1348,
            -1,
            1343,
            896302,
            -1,
            896307,
            1339,
            896308
          },
          lens {
            93,
            1,
            5,
            1,
            4
          },
          strands {
            minus,
            plus,
            minus,
            plus,
            minus,
            plus,
            minus,
            plus,
            minus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 38
          },
          {
            id str "e_value",
            value real { 778851832847449, 10, -24 }
          },
          {
            id str "bit_score",
            value real { 712929810225569, 10, -13 }
          },
          {
            id str "num_ident",
            value int 48
          }
        },
        segs denseg {
          dim 2,
          numseg 1,
          ids {
            local str "Query_1",
            general {
              db "Ceratitis_capitata",
              tag str "cercap_NW_004523420.1"
            }
          },
          starts {
            1377,
            1773729
          },
          lens {
            53
          },
          strands {
            plus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 37
          },
          {
            id str "e_value",
            value real { 280124944235158, 10, -23 }
          },
          {
            id str "bit_score",
            value real { 69446331370219, 10, -12 }
          },
          {
            id str "num_ident",
            value int 52
          }
        },
        segs denseg {
          dim 2,
          numseg 3,
          ids {
            local str "Query_1",
            general {
              db "Ceratitis_capitata",
              tag str "cercap_NW_004524040.1"
            }
          },
          starts {
            1340,
            19296,
            1395,
            -1,
            1396,
            19351
          },
          lens {
            55,
            1,
            3
          },
          strands {
            plus,
            plus,
            plus,
            plus,
            plus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 32
          },
          {
            id str "e_value",
            value real { 168591807672124, 10, -20 }
          },
          {
            id str "bit_score",
            value real { 602130831085297, 10, -13 }
          },
          {
            id str "num_ident",
            value int 34
          }
        },
        segs denseg {
          dim 2,
          numseg 1,
          ids {
            local str "Query_1",
            general {
              db "Ceratitis_capitata",
              tag str "cercap_NW_004522866.1"
            }
          },
          starts {
            1341,
            6190535
          },
          lens {
            35
          },
          strands {
            minus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 30
          },
          {
            id str "e_value",
            value real { 218087282494377, 10, -19 }
          },
          {
            id str "bit_score",
            value real { 565197838038539, 10, -13 }
          },
          {
            id str "num_ident",
            value int 39
          }
        },
        segs denseg {
          dim 2,
          numseg 3,
          ids {
            local str "Query_1",
            general {
              db "Ceratitis_capitata",
              tag str "cercap_NW_004523902.1"
            }
          },
          starts {
            464,
            5052909,
            -1,
            5052942,
            497,
            5052943
          },
          lens {
            33,
            1,
            9
          },
          strands {
            plus,
            plus,
            plus,
            plus,
            plus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 28
          },
          {
            id str "e_value",
            value real { 282113724519048, 10, -18 }
          },
          {
            id str "bit_score",
            value real { 528264844991782, 10, -13 }
          },
          {
            id str "num_ident",
            value int 28
          }
        },
        segs denseg {
          dim 2,
          numseg 1,
          ids {
            local str "Query_1",
            general {
              db "Ceratitis_capitata",
              tag str "cercap_NW_004524057.1"
            }
          },
          starts {
            1303,
            1372855
          },
          lens {
            28
          },
          strands {
            plus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 1225
          },
          {
            id str "e_value",
            value real { 0, 10, 0 }
          },
          {
            id str "bit_score",
            value real { 226326611834761, 10, -11 }
          },
          {
            id str "num_ident",
            value int 1225
          }
        },
        segs denseg {
          dim 2,
          numseg 1,
          ids {
            local str "Query_2",
            general {
              db "Anoplophora_glabripennis",
              tag str "anogla_Scaffold1"
            }
          },
          starts {
            504,
            134294
          },
          lens {
            1225
          },
          strands {
            minus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 479
          },
          {
            id str "e_value",
            value real { 0, 10, 0 }
          },
          {
            id str "bit_score",
            value real { 885665477703559, 10, -12 }
          },
          {
            id str "num_ident",
            value int 479
          }
        },
        segs denseg {
          dim 2,
          numseg 1,
          ids {
            local str "Query_2",
            general {
              db "Anoplophora_glabripennis",
              tag str "anogla_Scaffold1"
            }
          },
          starts {
            28,
            140159
          },
          lens {
            479
          },
          strands {
            minus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 31
          },
          {
            id str "e_value",
            value real { 545085938572267, 10, -20 }
          },
          {
            id str "bit_score",
            value real { 583664334561918, 10, -13 }
          },
          {
            id str "num_ident",
            value int 31
          }
        },
        segs denseg {
          dim 2,
          numseg 1,
          ids {
            local str "Query_2",
            general {
              db "Anoplophora_glabripennis",
              tag str "anogla_Scaffold1"
            }
          },
          starts {
            0,
            147265
          },
          lens {
            31
          },
          strands {
            minus,
            plus
          }
        }
      }
    },
    masks {
      {
        locations {
          packed-int {
            {
              from 0,
              to 154,
              id local str "Query_1"
            },
            {
              from 577,
              to 639,
              id local str "Query_1"
            },
            {
              from 695,
              to 755,
              id local str "Query_1"
            },
            {
              from 837,
              to 900,
              id local str "Query_1"
            },
            {
              from 1016,
              to 1037,
              id local str "Query_1"
            },
            {
              from 1884,
              to 1917,
              id local str "Query_1"
            }
          }
        },
        frame plus1
      },
      {
        locations {
          packed-int {
            {
              from 979,
              to 985,
              id local str "Query_2"
            },
            {
              from 1129,
              to 1191,
              id local str "Query_2"
            },
            {
              from 1704,
              to 1719,
              id local str "Query_2"
            }
          }
        },
        frame plus1
      }
    },
    ka-blocks {
      {
        lambda { 133270576282382, 10, -14 },
        k { 620991117264207, 10, -15 },
        h { 112409184650115, 10, -14 },
        gapped FALSE
      },
      {
        lambda { 128, 10, -2 },
        k { 46, 10, -2 },
        h { 85, 10, -2 },
        gapped TRUE
      }
    },
    search-stats {
      "Effective search space: 2253100761450",
      "Effective search space used: 2253100761450",
      "Length adjustment: 30"
    }
  }
}
