Blast4-archive ::= {
  request {
    ident "2.2.29+",
    body queue-search {
      program "blastn",
      service "megablast",
      queries bioseq-set {
        seq-set {
          seq {
            id {
              local str "Query_1"
            },
            descr {
              user {
                type str "CFastaReader",
                data {
                  {
                    label str "DefLine",
                    data str ">Contig1"
                  }
                }
              },
              title "Contig1"
            },
            inst {
              repr raw,
              mol na,
              length 41,
              seq-data ncbi2na '48AB0E96E4AAC030BB0F00'H
            }
          },
          seq {
            id {
              local str "Query_2"
            },
            descr {
              user {
                type str "CFastaReader",
                data {
                  {
                    label str "DefLine",
                    data str ">Contig2"
                  }
                }
              },
              title "Contig2"
            },
            inst {
              repr raw,
              mol na,
              length 53,
              seq-data ncbi2na 'F2F0299FD7F6EF934413FDD87140'H
            }
          }
        }
      },
      subject database "Agla_Btl03082013.genome_new_ids.fa
 Aros01112013-genome_new_ids.fa Ccap01172013-genome_new_ids.fa
 Clec_Bbug02212013.genome_new_ids.fa diaci1.1_new_ids.fa
 Edan07162013.scaffolds_new_ids.fa Eaff_11172013.genome_new_ids.fa
 Focc_FINAL.scaffolds_new_ids.fa Lful_Scha04012013-genome_new_ids.fa
 Ldec.genome.10062013_new_ids.fa Ofas.scaffolds_new_ids.fa
 Oabi11242013.genome_new_ids.fa Pven10162013.scaffolds_new_ids.fa
 Ptep01282013.genome_new_ids.fa Tpre_FINAL.scaffolds_new_ids.fa",
      algorithm-options {
        {
          name "EvalueThreshold",
          value cutoff e-value { 1, 10, 1 }
        },
        {
          name "MaskAtHash",
          value boolean TRUE
        },
        {
          name "DustFilteringLevel",
          value integer 20
        },
        {
          name "DustFilteringWindow",
          value integer 64
        },
        {
          name "DustFilteringLinker",
          value integer 1
        },
        {
          name "UngappedMode",
          value boolean FALSE
        },
        {
          name "HitlistSize",
          value integer 500
        },
        {
          name "EffectiveSearchSpace",
          value big-integer 137779911164
        }
      }
    }
  },
  results {
    alignments {
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 41
          },
          {
            id str "e_value",
            value real { 1023692029329, 10, -24 }
          },
          {
            id str "bit_score",
            value real { 768329299795705, 10, -13 }
          },
          {
            id str "num_ident",
            value int 41
          }
        },
        segs denseg {
          dim 2,
          numseg 1,
          ids {
            local str "Query_1",
            general {
              db "Anoplophora_glabripennis",
              tag str "anogla_Scaffold1"
            }
          },
          starts {
            0,
            135111
          },
          lens {
            41
          },
          strands {
            minus,
            plus
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 53
          },
          {
            id str "e_value",
            value real { 405743332661923, 10, -33 }
          },
          {
            id str "bit_score",
            value real { 98992725807625, 10, -12 }
          },
          {
            id str "num_ident",
            value int 53
          }
        },
        segs denseg {
          dim 2,
          numseg 1,
          ids {
            local str "Query_2",
            general {
              db "Anoplophora_glabripennis",
              tag str "anogla_Scaffold1"
            }
          },
          starts {
            0,
            135058
          },
          lens {
            53
          },
          strands {
            minus,
            plus
          }
        }
      }
    },
    masks {
    },
    ka-blocks {
      {
        lambda { 133270576282382, 10, -14 },
        k { 620991117264207, 10, -15 },
        h { 112409184650115, 10, -14 },
        gapped FALSE
      },
      {
        lambda { 128, 10, -2 },
        k { 46, 10, -2 },
        h { 85, 10, -2 },
        gapped TRUE
      }
    },
    search-stats {
      "Effective search space: 137779911164",
      "Effective search space used: 137779911164",
      "Length adjustment: 27"
    }
  }
}
