Blast4-archive ::= {
  request {
    ident "2.2.29+",
    body queue-search {
      program "tblastn",
      service "plain",
      queries bioseq-set {
        seq-set {
          seq {
            id {
              local str "Query_1"
            },
            descr {
              user {
                type str "CFastaReader",
                data {
                  {
                    label str "DefLine",
                    data str ">gi|5524211|gb|AAD44166.1| cytochrome b [Elephas
 maximus maximus]"
                  }
                }
              },
              title "gi|5524211|gb|AAD44166.1| cytochrome b [Elephas maximus
 maximus]"
            },
            inst {
              repr raw,
              mol aa,
              length 284,
              seq-data ncbieaa "LCLYTHIGRNIYYGSYLYSETWNTGIMLLLITMATAFMGYVLPWGQ
MSFWGATVITNLFSAIPYIGTNLVEWIWGGFSVDKATLNRFFAFHFILPFTMVALAGVHLTFLHETGSNNPLGLTSDS
DKIPFHPYYTIKDFLGLLILILLLLLLALLSPDMLGDPDNHMPADPLNTPLHIKPEWYFLFAYAILRSVPNKLGGVLA
LFLSIVILGLMPFLHTSKHRSMMLRPLSQALFWTLTMDLLTLTWIGSQPVEYPYTIIGQMASILYFSIILAFLPIAGX
IENY"
            }
          }
        }
      },
      subject database "Agla_Btl03082013.genome_new_ids.fa
 Ccap01172013-genome_new_ids.fa",
      algorithm-options {
        {
          name "EvalueThreshold",
          value cutoff e-value { 1, 10, 1 }
        },
        {
          name "DbGeneticCode",
          value integer 1
        },
        {
          name "UngappedMode",
          value boolean FALSE
        },
        {
          name "SumStatistics",
          value boolean TRUE
        },
        {
          name "LongestIntronLength",
          value integer 0
        },
        {
          name "MaskAtHash",
          value boolean FALSE
        },
        {
          name "SegFilteringWindow",
          value integer 12
        },
        {
          name "SegFilteringLocut",
          value real { 22, 10, -1 }
        },
        {
          name "SegFilteringHicut",
          value real { 25, 10, -1 }
        },
        {
          name "WordThreshold",
          value integer 13
        },
        {
          name "WindowSize",
          value integer 40
        },
        {
          name "HitlistSize",
          value integer 500
        },
        {
          name "CompositionBasedStats",
          value integer 2
        },
        {
          name "SmithWatermanMode",
          value boolean FALSE
        },
        {
          name "EffectiveSearchSpace",
          value big-integer 63355283840
        }
      }
    }
  },
  results {
    alignments {
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 718
          },
          {
            id str "e_value",
            value real { 456965099031941, 10, -97 }
          },
          {
            id str "bit_score",
            value real { 281181527788704, 10, -12 }
          },
          {
            id str "num_ident",
            value int 145
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 192
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold526"
              }
            },
            loc {
              int {
                from 0,
                to 267,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 405809,
                to 406612,
                strand plus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold526"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 555
          },
          {
            id str "e_value",
            value real { 218807918571162, 10, -75 }
          },
          {
            id str "bit_score",
            value real { 218393996914175, 10, -12 }
          },
          {
            id str "num_ident",
            value int 110
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 147
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold1107"
              }
            },
            loc {
              int {
                from 30,
                to 225,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 100807,
                to 101394,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold1107"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 85
          },
          {
            id str "e_value",
            value real { 359963112812614, 10, -15 }
          },
          {
            id str "bit_score",
            value real { 37350196233019, 10, -12 }
          },
          {
            id str "num_ident",
            value int 19
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 31
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold1107"
              }
            },
            loc {
              int {
                from 217,
                to 267,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 100683,
                to 100835,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold1107"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 361
          },
          {
            id str "sum_n",
            value int 2
          },
          {
            id str "e_value",
            value real { 705085543422492, 10, -65 }
          },
          {
            id str "bit_score",
            value real { 143665279186209, 10, -12 }
          },
          {
            id str "num_ident",
            value int 72
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 99
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523321.1"
              }
            },
            loc {
              int {
                from 15,
                to 26,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 1092412,
                to 1092447,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523321.1"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523321.1"
              }
            },
            loc {
              empty local str "Query_1",
              int {
                from 1092403,
                to 1092411,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523321.1"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523321.1"
              }
            },
            loc {
              int {
                from 27,
                to 136,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 1092073,
                to 1092402,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523321.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 197
          },
          {
            id str "sum_n",
            value int 2
          },
          {
            id str "e_value",
            value real { 705085543422492, 10, -65 }
          },
          {
            id str "bit_score",
            value real { 804925487357626, 10, -13 }
          },
          {
            id str "num_ident",
            value int 39
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 53
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523321.1"
              }
            },
            loc {
              int {
                from 162,
                to 226,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 1091802,
                to 1091996,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523321.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 402
          },
          {
            id str "e_value",
            value real { 36004155914674, 10, -54 }
          },
          {
            id str "bit_score",
            value real { 15945846179882, 10, -11 }
          },
          {
            id str "num_ident",
            value int 87
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 125
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold727"
              }
            },
            loc {
              int {
                from 0,
                to 12,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 81750,
                to 81788,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold727"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold727"
              }
            },
            loc {
              int {
                from 13,
                to 13,
                strand unknown,
                id local str "Query_1"
              },
              empty general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold727"
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold727"
              }
            },
            loc {
              int {
                from 14,
                to 178,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 81255,
                to 81749,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold727"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 400
          },
          {
            id str "e_value",
            value real { 709669856594541, 10, -55 }
          },
          {
            id str "bit_score",
            value real { 158688062646985, 10, -12 }
          },
          {
            id str "num_ident",
            value int 88
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 129
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523376.1"
              }
            },
            loc {
              int {
                from 62,
                to 181,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 299819,
                to 300178,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523376.1"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523376.1"
              }
            },
            loc {
              int {
                from 182,
                to 183,
                strand unknown,
                id local str "Query_1"
              },
              empty general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523376.1"
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523376.1"
              }
            },
            loc {
              int {
                from 184,
                to 267,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 299567,
                to 299818,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523376.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 277
          },
          {
            id str "e_value",
            value real { 557974952567306, 10, -39 }
          },
          {
            id str "bit_score",
            value real { 111308514809151, 10, -12 }
          },
          {
            id str "num_ident",
            value int 55
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 78
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523376.1"
              }
            },
            loc {
              int {
                from 0,
                to 100,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 300061,
                to 300363,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523376.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 378
          },
          {
            id str "e_value",
            value real { 490565235700711, 10, -52 }
          },
          {
            id str "bit_score",
            value real { 150213671976804, 10, -12 }
          },
          {
            id str "num_ident",
            value int 84
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 125
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523732.1"
              }
            },
            loc {
              int {
                from 77,
                to 133,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 208460,
                to 208630,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523732.1"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523732.1"
              }
            },
            loc {
              int {
                from 134,
                to 135,
                strand unknown,
                id local str "Query_1"
              },
              empty general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523732.1"
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523732.1"
              }
            },
            loc {
              int {
                from 136,
                to 219,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 208208,
                to 208459,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523732.1"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523732.1"
              }
            },
            loc {
              int {
                from 220,
                to 221,
                strand unknown,
                id local str "Query_1"
              },
              empty general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523732.1"
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523732.1"
              }
            },
            loc {
              int {
                from 222,
                to 234,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 208169,
                to 208207,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523732.1"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523732.1"
              }
            },
            loc {
              int {
                from 235,
                to 236,
                strand unknown,
                id local str "Query_1"
              },
              empty general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523732.1"
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523732.1"
              }
            },
            loc {
              int {
                from 237,
                to 266,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 208079,
                to 208168,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523732.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 169
          },
          {
            id str "e_value",
            value real { 136030207072466, 10, -25 }
          },
          {
            id str "bit_score",
            value real { 697069606100767, 10, -13 }
          },
          {
            id str "num_ident",
            value int 35
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 51
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523732.1"
              }
            },
            loc {
              int {
                from 24,
                to 90,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 208584,
                to 208784,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523732.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 266
          },
          {
            id str "sum_n",
            value int 2
          },
          {
            id str "e_value",
            value real { 496314699649398, 10, -48 }
          },
          {
            id str "bit_score",
            value real { 10707131947406, 10, -11 }
          },
          {
            id str "num_ident",
            value int 65
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 105
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523928.1"
              }
            },
            loc {
              int {
                from 46,
                to 136,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 29566,
                to 29838,
                strand plus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523928.1"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523928.1"
              }
            },
            loc {
              int {
                from 137,
                to 182,
                strand unknown,
                id local str "Query_1"
              },
              empty general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523928.1"
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523928.1"
              }
            },
            loc {
              int {
                from 183,
                to 231,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 29839,
                to 29985,
                strand plus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523928.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 145
          },
          {
            id str "sum_n",
            value int 2
          },
          {
            id str "e_value",
            value real { 496314699649398, 10, -48 }
          },
          {
            id str "bit_score",
            value real { 604621707880602, 10, -13 }
          },
          {
            id str "num_ident",
            value int 26
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 40
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523928.1"
              }
            },
            loc {
              int {
                from 0,
                to 48,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 29423,
                to 29569,
                strand plus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523928.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 321
          },
          {
            id str "e_value",
            value real { 16218655840757, 10, -43 }
          },
          {
            id str "bit_score",
            value real { 128257296149514, 10, -12 }
          },
          {
            id str "num_ident",
            value int 66
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 85
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold786"
              }
            },
            loc {
              int {
                from 5,
                to 115,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 37498,
                to 37830,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold786"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 292
          },
          {
            id str "e_value",
            value real { 890664354993544, 10, -41 }
          },
          {
            id str "bit_score",
            value real { 117086508447911, 10, -12 }
          },
          {
            id str "num_ident",
            value int 59
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 76
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold17"
              }
            },
            loc {
              int {
                from 0,
                to 95,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 391126,
                to 391413,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold17"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 290
          },
          {
            id str "e_value",
            value real { 157296620355037, 10, -40 }
          },
          {
            id str "bit_score",
            value real { 116316109296076, 10, -12 }
          },
          {
            id str "num_ident",
            value int 59
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 81
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold128"
              }
            },
            loc {
              int {
                from 0,
                to 110,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 838236,
                to 838568,
                strand plus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold128"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 241
          },
          {
            id str "e_value",
            value real { 175956013311847, 10, -34 }
          },
          {
            id str "bit_score",
            value real { 974413300761261, 10, -13 }
          },
          {
            id str "num_ident",
            value int 56
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 74
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold296"
              }
            },
            loc {
              int {
                from 0,
                to 85,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 795,
                to 1052,
                strand plus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold296"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold296"
              }
            },
            loc {
              int {
                from 86,
                to 86,
                strand unknown,
                id local str "Query_1"
              },
              empty general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold296"
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold296"
              }
            },
            loc {
              int {
                from 87,
                to 101,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 1053,
                to 1097,
                strand plus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold296"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 218
          },
          {
            id str "e_value",
            value real { 132354536844873, 10, -31 }
          },
          {
            id str "bit_score",
            value real { 88581739830027, 10, -12 }
          },
          {
            id str "num_ident",
            value int 39
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 52
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold511"
              }
            },
            loc {
              int {
                from 74,
                to 136,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 84668,
                to 84856,
                strand plus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold511"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 213
          },
          {
            id str "e_value",
            value real { 510163612717333, 10, -31 }
          },
          {
            id str "bit_score",
            value real { 866557419504402, 10, -13 }
          },
          {
            id str "num_ident",
            value int 43
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 60
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004524533.1"
              }
            },
            loc {
              int {
                from 154,
                to 216,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 237837,
                to 238025,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004524533.1"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004524533.1"
              }
            },
            loc {
              empty local str "Query_1",
              int {
                from 237822,
                to 237836,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004524533.1"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004524533.1"
              }
            },
            loc {
              int {
                from 217,
                to 233,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 237771,
                to 237821,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004524533.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 88
          },
          {
            id str "e_value",
            value real { 173107188018998, 10, -15 }
          },
          {
            id str "bit_score",
            value real { 385057949607711, 10, -13 }
          },
          {
            id str "num_ident",
            value int 18
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 30
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004524533.1"
              }
            },
            loc {
              int {
                from 72,
                to 110,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 226748,
                to 226864,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004524533.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 195
          },
          {
            id str "sum_n",
            value int 2
          },
          {
            id str "e_value",
            value real { 151880402380733, 10, -30 }
          },
          {
            id str "bit_score",
            value real { 797221495839279, 10, -13 }
          },
          {
            id str "num_ident",
            value int 45
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 56
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold125"
              }
            },
            loc {
              int {
                from 107,
                to 153,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 493325,
                to 493465,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold125"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold125"
              }
            },
            loc {
              int {
                from 154,
                to 156,
                strand unknown,
                id local str "Query_1"
              },
              empty general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold125"
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold125"
              }
            },
            loc {
              int {
                from 157,
                to 171,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 493280,
                to 493324,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold125"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold125"
              }
            },
            loc {
              empty local str "Query_1",
              int {
                from 493271,
                to 493279,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold125"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold125"
              }
            },
            loc {
              int {
                from 172,
                to 194,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 493202,
                to 493270,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold125"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 64
          },
          {
            id str "sum_n",
            value int 2
          },
          {
            id str "e_value",
            value real { 151880402380733, 10, -30 }
          },
          {
            id str "bit_score",
            value real { 292610051387546, 10, -13 }
          },
          {
            id str "num_ident",
            value int 12
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 17
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold125"
              }
            },
            loc {
              int {
                from 84,
                to 105,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 493467,
                to 493532,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold125"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 205
          },
          {
            id str "e_value",
            value real { 519784004010211, 10, -30 }
          },
          {
            id str "bit_score",
            value real { 835741453431014, 10, -13 }
          },
          {
            id str "num_ident",
            value int 43
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 57
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523902.1"
              }
            },
            loc {
              int {
                from 154,
                to 213,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 2526496,
                to 2526675,
                strand plus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523902.1"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523902.1"
              }
            },
            loc {
              int {
                from 214,
                to 215,
                strand unknown,
                id local str "Query_1"
              },
              empty general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523902.1"
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523902.1"
              }
            },
            loc {
              int {
                from 216,
                to 227,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 2526676,
                to 2526711,
                strand plus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523902.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 197
          },
          {
            id str "e_value",
            value real { 426092553434134, 10, -29 }
          },
          {
            id str "bit_score",
            value real { 804925487357626, 10, -13 }
          },
          {
            id str "num_ident",
            value int 40
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 50
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523847.1"
              }
            },
            loc {
              int {
                from 33,
                to 89,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 3650889,
                to 3651059,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523847.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 149
          },
          {
            id str "e_value",
            value real { 463419349051149, 10, -23 }
          },
          {
            id str "bit_score",
            value real { 620029690917296, 10, -13 }
          },
          {
            id str "num_ident",
            value int 33
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 43
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523925.1"
              }
            },
            loc {
              int {
                from 39,
                to 95,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 2476325,
                to 2476495,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523925.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 121
          },
          {
            id str "sum_n",
            value int 2
          },
          {
            id str "e_value",
            value real { 235260270686562, 10, -22 }
          },
          {
            id str "bit_score",
            value real { 512173809660437, 10, -13 }
          },
          {
            id str "num_ident",
            value int 25
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 33
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold59"
              }
            },
            loc {
              int {
                from 30,
                to 68,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 309560,
                to 309676,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold59"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 65
          },
          {
            id str "sum_n",
            value int 2
          },
          {
            id str "e_value",
            value real { 235260270686562, 10, -22 }
          },
          {
            id str "bit_score",
            value real { 29646204714672, 10, -12 }
          },
          {
            id str "num_ident",
            value int 15
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 20
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold59"
              }
            },
            loc {
              int {
                from 0,
                to 30,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 309673,
                to 309765,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold59"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 102
          },
          {
            id str "sum_n",
            value int 2
          },
          {
            id str "e_value",
            value real { 13778069549057, 10, -20 }
          },
          {
            id str "bit_score",
            value real { 43898589023614, 10, -12 }
          },
          {
            id str "num_ident",
            value int 21
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 24
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523309.1"
              }
            },
            loc {
              int {
                from 177,
                to 205,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 1150275,
                to 1150361,
                strand plus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523309.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 77
          },
          {
            id str "sum_n",
            value int 2
          },
          {
            id str "e_value",
            value real { 13778069549057, 10, -20 }
          },
          {
            id str "bit_score",
            value real { 342685996256802, 10, -13 }
          },
          {
            id str "num_ident",
            value int 15
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 20
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523309.1"
              }
            },
            loc {
              int {
                from 162,
                to 185,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 1150229,
                to 1150300,
                strand plus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523309.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 134
          },
          {
            id str "e_value",
            value real { 377854231931546, 10, -21 }
          },
          {
            id str "bit_score",
            value real { 562249754529693, 10, -13 }
          },
          {
            id str "num_ident",
            value int 25
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 41
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523714.1"
              }
            },
            loc {
              int {
                from 24,
                to 72,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 1702699,
                to 1702845,
                strand plus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523714.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 121
          },
          {
            id str "sum_n",
            value int 2
          },
          {
            id str "e_value",
            value real { 68231220642253, 10, -20 }
          },
          {
            id str "bit_score",
            value real { 512173809660437, 10, -13 }
          },
          {
            id str "num_ident",
            value int 26
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 34
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold9"
              }
            },
            loc {
              int {
                from 26,
                to 68,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 698107,
                to 698235,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold9"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 52
          },
          {
            id str "sum_n",
            value int 2
          },
          {
            id str "e_value",
            value real { 68231220642253, 10, -20 }
          },
          {
            id str "bit_score",
            value real { 246386102277464, 10, -13 }
          },
          {
            id str "num_ident",
            value int 13
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 18
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold9"
              }
            },
            loc {
              int {
                from 0,
                to 27,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 698231,
                to 698314,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold9"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 123
          },
          {
            id str "e_value",
            value real { 82442743085304, 10, -19 }
          },
          {
            id str "bit_score",
            value real { 519877801178785, 10, -13 }
          },
          {
            id str "num_ident",
            value int 25
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 36
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004524279.1"
              }
            },
            loc {
              int {
                from 63,
                to 107,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 60562,
                to 60696,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004524279.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 104
          },
          {
            id str "e_value",
            value real { 199748370480828, 10, -17 }
          },
          {
            id str "bit_score",
            value real { 446689881754487, 10, -13 }
          },
          {
            id str "num_ident",
            value int 22
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 32
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold1201"
              }
            },
            loc {
              int {
                from 177,
                to 220,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 2323,
                to 2454,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold1201"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 102
          },
          {
            id str "e_value",
            value real { 292732088526343, 10, -17 }
          },
          {
            id str "bit_score",
            value real { 43898589023614, 10, -12 }
          },
          {
            id str "num_ident",
            value int 18
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 30
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004524234.1"
              }
            },
            loc {
              int {
                from 0,
                to 35,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 905101,
                to 905208,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004524234.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 100
          },
          {
            id str "e_value",
            value real { 580214894956088, 10, -17 }
          },
          {
            id str "bit_score",
            value real { 431281898717793, 10, -13 }
          },
          {
            id str "num_ident",
            value int 24
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 30
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold116"
              }
            },
            loc {
              int {
                from 8,
                to 15,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 847912,
                to 847935,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold116"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold116"
              }
            },
            loc {
              empty local str "Query_1",
              int {
                from 847909,
                to 847911,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold116"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold116"
              }
            },
            loc {
              int {
                from 16,
                to 51,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 847801,
                to 847908,
                strand minus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold116"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 99
          },
          {
            id str "e_value",
            value real { 788768485644626, 10, -17 }
          },
          {
            id str "bit_score",
            value real { 42742990295862, 10, -12 }
          },
          {
            id str "num_ident",
            value int 18
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 22
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004522866.1"
              }
            },
            loc {
              int {
                from 157,
                to 182,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 4068188,
                to 4068265,
                strand plus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004522866.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 88
          },
          {
            id str "e_value",
            value real { 165743146114684, 10, -15 }
          },
          {
            id str "bit_score",
            value real { 385057949607711, 10, -13 }
          },
          {
            id str "num_ident",
            value int 16
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 26
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523858.1"
              }
            },
            loc {
              int {
                from 88,
                to 117,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 145162,
                to 145251,
                strand plus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523858.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 87
          },
          {
            id str "e_value",
            value real { 243460247051991, 10, -15 }
          },
          {
            id str "bit_score",
            value real { 381205953848537, 10, -13 }
          },
          {
            id str "num_ident",
            value int 15
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 19
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold1"
              }
            },
            loc {
              int {
                from 158,
                to 179,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 3854044,
                to 3854109,
                strand plus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 82
          },
          {
            id str "e_value",
            value real { 941318110611176, 10, -15 }
          },
          {
            id str "bit_score",
            value real { 36194597505267, 10, -12 }
          },
          {
            id str "num_ident",
            value int 16
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 19
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Anoplophora_glabripennis",
                tag str "anogla_Scaffold36"
              }
            },
            loc {
              int {
                from 167,
                to 187,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 831558,
                to 831620,
                strand plus,
                id general {
                  db "Anoplophora_glabripennis",
                  tag str "anogla_Scaffold36"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 78
          },
          {
            id str "e_value",
            value real { 232174276379887, 10, -14 }
          },
          {
            id str "bit_score",
            value real { 346537992015976, 10, -13 }
          },
          {
            id str "num_ident",
            value int 15
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 28
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004524527.1"
              }
            },
            loc {
              int {
                from 222,
                to 267,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 10221,
                to 10358,
                strand minus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004524527.1"
                }
              }
            }
          }
        }
      },
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 76
          },
          {
            id str "e_value",
            value real { 518815526158878, 10, -14 }
          },
          {
            id str "bit_score",
            value real { 338834000497628, 10, -13 }
          },
          {
            id str "num_ident",
            value int 19
          },
          {
            id str "comp_adjustment_method",
            value int 2
          },
          {
            id str "num_positives",
            value int 44
          }
        },
        segs std {
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523880.1"
              }
            },
            loc {
              int {
                from 2,
                to 6,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 3454918,
                to 3454932,
                strand plus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523880.1"
                }
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523880.1"
              }
            },
            loc {
              int {
                from 7,
                to 9,
                strand unknown,
                id local str "Query_1"
              },
              empty general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523880.1"
              }
            }
          },
          {
            dim 2,
            ids {
              local str "Query_1",
              general {
                db "Ceratitis_capitata",
                tag str "cercap_NW_004523880.1"
              }
            },
            loc {
              int {
                from 10,
                to 74,
                strand unknown,
                id local str "Query_1"
              },
              int {
                from 3454933,
                to 3455127,
                strand plus,
                id general {
                  db "Ceratitis_capitata",
                  tag str "cercap_NW_004523880.1"
                }
              }
            }
          }
        }
      }
    },
    masks {
      {
        locations {
          packed-int {
            {
              from 138,
              to 153,
              id local str "Query_1"
            },
            {
              from 235,
              to 244,
              id local str "Query_1"
            }
          }
        },
        frame notset
      }
    },
    ka-blocks {
      {
        lambda { 327505938484236, 10, -15 },
        k { 143329546844576, 10, -15 },
        h { 472118281449686, 10, -15 },
        gapped FALSE
      },
      {
        lambda { 267, 10, -3 },
        k { 41, 10, -3 },
        h { 14, 10, -2 },
        gapped TRUE
      }
    },
    search-stats {
      "Effective search space: 63355283840",
      "Effective search space used: 63355283840",
      "Length adjustment: 124"
    }
  }
}
